### ISSUE TITLE
Declaration or statement expected

### ISSUE THREAD

**Issue by horacio-pedro** [redexp/express-engine-jsx#11]
When rendering the page I always get the same error:

Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?

![Screenshot from 2024-02-29 05-25-29](https://github.com/redexp/express-engine-jsx/assets/46960527/c11e2152-f0fb-42ab-b51a-e4a235856439)

I've modified it a bit but I'm basing it on the example from the documentation.

**App.jsx**
```
<html lang={lang}>
  <head>
    <meta charset="UTF-8"/>
    <title>{title}</title>
  </head>
  <body>{children}</body>
</html>
```

**users.jsx**
```
const App = require('../../App')

<App>
  <ul class="users">
    {users.map(user => (
      <li key={user}>{user.name}</li>
    ))}
  </ul>
</App>
```

**Comment by redexp** [comment]
I think it's because you have typescript config in your project and maybe typescript don't like values without assignment. Usually jsx code passing somewhere like to `return <App>...</App>` or to some var `const inp = <input/>`, but not in our case. I'v tried to google how to suppress ts1128 with tsconfig or with tslint but no luck
